name: portfolio
description: My Personal portfolio project, can run in all the platforms.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  file_saver: ^0.2.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  get_it: ^7.6.0
  intl: ^0.18.1
  liquid_progress_indicator_v2: ^0.5.0
  palette_generator: ^0.3.3+3
  responsive_builder: ^0.7.0
  url_launcher: ^6.1.11
  very_good_analysis: ^5.0.0+1
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MPLUSRounded1c-Black.ttf
          weight: 900
