name: portfolio
description: My Personal portfolio project, can run in all the platforms.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:

  animated_text_kit:
    git:
      url: https://github.com/incrediblezayed/Animated-Text-Kit.git
      ref: master
  collection: ^1.17.1
  dio: ^5.2.1+1
  file_saver: ^0.2.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  responsive_builder: ^0.7.0
  url_launcher: ^6.1.11
  very_good_analysis: ^5.0.0+1
  

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
