name: portfolio
description: My Personal portfolio project, can run in all the platforms.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cached_network_image: 3.4.1
  collection: ^1.19.1
  cupertino_icons: 1.0.8
  dio: ^5.8.0+1
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_widget_from_html: 0.17.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  intl: ^0.20.2
  liquid_progress_indicator_v2: 0.5.0
  portfolio_core_data:
    git:
      url: https://github.com/incrediblezayed/portfolio_core_data
      ref: main
  responsive_builder: 0.7.1
  url_launcher: ^6.3.2
    

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MPLUSRounded1c-Black.ttf
          weight: 900
