name: Build and Release Portfolio

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build:
    permissions:
      contents: write
      packages: write
    name: Build Portfolio
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.10.2"
      - run: ls -la
      - run: flutter pub get
      - run: flutter build apk --release
      - run: ls -la
      - run : cd build/app/outputs/apk/release
      - run: ls -la
      - name: Push Builds
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ github.ref_name }}
